"use client";
import { HubOpportunity, Market, Vocab } from "@/lib/types";
export const MARKET_DATA: Market[] = [
  { slug: "berlin", display_name: "Berlin", country: "Germany", region: "DACH", timezone: "Europe/Berlin", currency: "EUR", lat: 52.52, lng: 13.405 },
  { slug: "cologne", display_name: "Cologne", country: "Germany", region: "DACH", timezone: "Europe/Berlin", currency: "EUR", lat: 50.9375, lng: 6.9603 },
  { slug: "tel_aviv", display_name: "Tel Aviv", country: "Israel", region: "Med", timezone: "Asia/Tel_Aviv", currency: "ILS", lat: 32.0853, lng: 34.7818 },
  { slug: "brussels", display_name: "Brussels", country: "Belgium", region: "Benelux", timezone: "Europe/Brussels", currency: "EUR", lat: 50.8503, lng: 4.3517 },
  { slug: "vienna", display_name: "Vienna", country: "Austria", region: "DACH", timezone: "Europe/Vienna", currency: "EUR", lat: 48.2082, lng: 16.3738 },
  { slug: "zurich", display_name: "Zurich", country: "Switzerland", region: "DACH", timezone: "Europe/Zurich", currency: "CHF", lat: 47.3769, lng: 8.5417 },
  { slug: "amsterdam", display_name: "Amsterdam", country: "Netherlands", region: "Benelux", timezone: "Europe/Amsterdam", currency: "EUR", lat: 52.3676, lng: 4.9041 },
  { slug: "paris", display_name: "Paris", country: "France", region: "France", timezone: "Europe/Paris", currency: "EUR", lat: 48.8566, lng: 2.3522 },
  { slug: "lyon", display_name: "Lyon", country: "France", region: "France", timezone: "Europe/Paris", currency: "EUR", lat: 45.764, lng: 4.8357 },
  { slug: "stockholm", display_name: "Stockholm", country: "Sweden", region: "Nordics", timezone: "Europe/Stockholm", currency: "SEK", lat: 59.3293, lng: 18.0686 },
  { slug: "oslo", display_name: "Oslo", country: "Norway", region: "Nordics", timezone: "Europe/Oslo", currency: "NOK", lat: 59.9139, lng: 10.7522 },
  { slug: "copenhagen", display_name: "Copenhagen", country: "Denmark", region: "Nordics", timezone: "Europe/Copenhagen", currency: "DKK", lat: 55.6761, lng: 12.5683 },
  { slug: "athens", display_name: "Athens", country: "Greece", region: "Med", timezone: "Europe/Athens", currency: "EUR", lat: 37.9838, lng: 23.7275 },
  { slug: "tbilisi", display_name: "Tbilisi", country: "Georgia", region: "Caucasus", timezone: "Asia/Tbilisi", currency: "GEL", lat: 41.7151, lng: 44.8271 },
  { slug: "tokyo", display_name: "Tokyo", country: "Japan", region: "East_Asia", timezone: "Asia/Tokyo", currency: "JPY", lat: 35.6762, lng: 139.6503 },
  { slug: "seoul", display_name: "Seoul", country: "South Korea", region: "East_Asia", timezone: "Asia/Seoul", currency: "KRW", lat: 37.5665, lng: 126.978 },
  { slug: "warsaw", display_name: "Warsaw", country: "Poland", region: "CEE", timezone: "Europe/Warsaw", currency: "PLN", lat: 52.2297, lng: 21.0122 },
  { slug: "krakow", display_name: "Krakow", country: "Poland", region: "CEE", timezone: "Europe/Warsaw", currency: "PLN", lat: 50.0647, lng: 19.945 },
  { slug: "prague", display_name: "Prague", country: "Czech Republic", region: "CEE", timezone: "Europe/Prague", currency: "CZK", lat: 50.0755, lng: 14.4378 },
  { slug: "lisbon", display_name: "Lisbon", country: "Portugal", region: "Med", timezone: "Europe/Lisbon", currency: "EUR", lat: 38.7223, lng: -9.1393 },
  { slug: "barcelona", display_name: "Barcelona", country: "Spain", region: "Med", timezone: "Europe/Madrid", currency: "EUR", lat: 41.3851, lng: 2.1734 },
  { slug: "turin", display_name: "Turin", country: "Italy", region: "Med", timezone: "Europe/Rome", currency: "EUR", lat: 45.0703, lng: 7.6869 },
  { slug: "remote", display_name: "Remote", country: "Global", region: "remote", timezone: "UTC", currency: "EUR", lat: 0.0, lng: 0.0 },
];
export const VOCAB_DATA: Vocab[] = [
  { category: "type", value: "open_call", label: "Open Call", sort_order: 1 },
  { category: "type", value: "residency", label: "Residency", sort_order: 2 },
  { category: "type", value: "grant", label: "Grant / Funding", sort_order: 3 },
  { category: "type", value: "co_production", label: "Co-Production", sort_order: 4 },
  { category: "type", value: "commission", label: "Commission", sort_order: 5 },
  { category: "type", value: "festival_submission", label: "Festival Submission", sort_order: 6 },
  { category: "type", value: "award", label: "Award / Prize", sort_order: 7 },
  { category: "type", value: "lab_workshop", label: "Lab / Workshop", sort_order: 8 },
  { category: "type", value: "audition_job", label: "Audition / Job", sort_order: 9 },
  { category: "type", value: "mentorship", label: "Mentorship", sort_order: 10 },
  { category: "discipline", value: "dance", label: "Contemporary Dance", sort_order: 1 },
  { category: "discipline", value: "choreography", label: "Choreography", sort_order: 2 },
  { category: "discipline", value: "performance", label: "Performance Art", sort_order: 3 },
  { category: "discipline", value: "sound", label: "Experimental Sound", sort_order: 4 },
  { category: "discipline", value: "live_electronics", label: "Live Electronics", sort_order: 5 },
  { category: "discipline", value: "installation", label: "Sound & Light Installation", sort_order: 6 },
  { category: "discipline", value: "interdisciplinary", label: "Interdisciplinary / Hybrid", sort_order: 7 },
  { category: "funding_type", value: "cash_grant", label: "Cash Grant", sort_order: 1 },
  { category: "funding_type", value: "artist_fee", label: "Artist Fee", sort_order: 2 },
  { category: "funding_type", value: "stipend", label: "Living Stipend", sort_order: 3 },
  { category: "funding_type", value: "production_budget", label: "Production Budget", sort_order: 4 },
  { category: "funding_type", value: "in_kind", label: "In-Kind Support", sort_order: 5 },
  { category: "funding_type", value: "none", label: "Unfunded", sort_order: 6 },
  { category: "covers", value: "housing", label: "Housing / Accommodation", sort_order: 1 },
  { category: "covers", value: "travel", label: "Travel Expenses", sort_order: 2 },
  { category: "covers", value: "studio", label: "Studio Space", sort_order: 3 },
  { category: "covers", value: "tech", label: "Technical Equipment", sort_order: 4 },
  { category: "covers", value: "mentorship", label: "Mentorship / Dramaturgy", sort_order: 5 },
  { category: "covers", value: "per_diem", label: "Per Diem", sort_order: 6 },
  { category: "covers", value: "presentation", label: "Public Presentation", sort_order: 7 },
  { category: "career_stage", value: "emerging", label: "Emerging", sort_order: 1 },
  { category: "career_stage", value: "mid", label: "Mid-Career", sort_order: 2 },
  { category: "career_stage", value: "established", label: "Established", sort_order: 3 },
  { category: "career_stage", value: "any", label: "Any Stage", sort_order: 4 },
  { category: "region", value: "DACH", label: "DACH (Germany, Austria, Switzerland)", sort_order: 1 },
  { category: "region", value: "Benelux", label: "Benelux (Belgium, Netherlands, Luxembourg)", sort_order: 2 },
  { category: "region", value: "France", label: "France", sort_order: 3 },
  { category: "region", value: "Nordics", label: "Nordics", sort_order: 4 },
  { category: "region", value: "Med", label: "Mediterranean & Southern Europe", sort_order: 5 },
  { category: "region", value: "CEE", label: "Central & Eastern Europe", sort_order: 6 },
  { category: "region", value: "Caucasus", label: "Caucasus", sort_order: 7 },
  { category: "region", value: "East_Asia", label: "East Asia", sort_order: 8 },
  { category: "region", value: "remote", label: "Remote / Global", sort_order: 9 },
];

// Source ID to source name mapping
export const SOURCE_MAP: Record<string, string> = {
  "SRC165": "PACT Zollverein", "SRC163": "TanzFaktur Köln", "SRC002": "Uferstudios Berlin",
  "SRC003": "CTM Festival & Workspace", "SRC006": "Musicboard Berlin", "SRC211": "Kunstenfestivaldesarts",
  "SRC180": "Tanzquartier Wien (TQW)", "SRC017": "EMS Elektronmusikstudion", "SRC080": "Bimhuis & Muziekgebouw aan 't IJ",
  "SRC095": "Centre National de la Danse (CND Pantin)", "SRC190": "Bassiani & Horoom Cultural Space",
  "SRC001": "HAU Hebbel am Ufer", "SRC004": "Radialsystem V", "SRC005": "Tanzfabrik Berlin",
  "SRC007": "Sophiensæle", "SRC008": "Kulturrådet (Swedish Arts Council)", "SRC009": "Dansens Hus Stockholm",
  "SRC010": "EMS Elektronmusikstudion", "SRC011": "MDT Moderna Dansteatern", "SRC012": "Onassis Stegi",
  "SRC013": "Romantso Cultural Hub", "SRC014": "The Saison Foundation / Morishita Studio",
  "SRC015": "Tokyo Arts and Space (TOKAS)", "SRC016": "Seoul Dance Center", "SRC018": "Cricoteka Centre for the Documentation of Art",
  "SRC019": "Bimhuis & Muziekgebouw aan 't IJ", "SRC020": "Dansmakers / ICK Dans Amsterdam",
  "SRC021": "Stimuleringsfonds Creatieve Industrie", "SRC022": "Centre National de la Danse (CND Pantin)",
  "SRC023": "IRCAM", "SRC024": "Dansehallerne", "SRC025": "Alice cph", "SRC026": "Mercat de les Flors",
  "SRC027": "Hangar Barcelona", "SRC028": "La Caldera", "SRC029": "Institut del Teatre",
  "SRC030": "Les Subsistances", "SRC031": "Lavanderia a Vapore", "SRC032": "Studio ALTA",
  "SRC033": "Nowy Teatr", "SRC034": "Body/Mind Festival", "SRC035": "Culturgest",
  "SRC036": "Galeria Zé dos Bois (ZDB)", "SRC037": "TanzFaktur Köln", "SRC038": "Kunststiftung NRW",
  "SRC039": "PACT Zollverein", "SRC040": "Akademie der Künste der Welt (ADKDW Köln)",
  "SRC041": "Tanzquartier Wien (TQW)", "SRC042": "brut Wien", "SRC043": "ImPulsTanz Vienna International Dance Festival",
  "SRC044": "Rote Fabrik", "SRC045": "Gessnerallee Zürich", "SRC046": "Pro Helvetia",
  "SRC047": "Bassiani & Horoom Cultural Space", "SRC048": "Khidi Cultural Platform",
  "SRC049": "Kelim Choreography Center", "SRC050": "Tmuna Theater", "SRC051": "Suzanne Dellal Centre",
  "SRC052": "Mifal HaPais Arts Council", "SRC053": "Hazira Performance Art Arena", "SRC054": "Beursschouwburg",
  "SRC055": "Kunstenfestivaldesarts", "SRC056": "Charleroi danse (La Raffinerie)", "SRC057": "Q-O2 Workspace for Experimental Music and Sound Art",
};