'use client'

import { useState } from 'react'
import Link from 'next/link'
import { Bookmark, CalendarDays, Check, ChevronDown, Globe, Home, Instagram, Mail, Map, Play, Search, ShieldCheck, UserRound, Video, X } from 'lucide-react'

const opportunities = [
  { slug: 'body-time-space-2027', title: 'Body Time Space Residency 2027', source: 'Radialsystem', city: 'Berlin', type: 'Residency', amount: '€2,000–5,000', deadline: '3 days', tone: 'urgent', fit: 'Eligible' },
  { slug: 'new-music-commission', title: 'New Music Commission', source: 'STEIM', city: 'Amsterdam', type: 'Commission', amount: '€5,000', deadline: '12 days', tone: 'accent', fit: 'Eligible' },
  { slug: 'brussels-performance-call', title: 'Brussels Performance Call', source: 'Les Brigittines', city: 'Brussels', type: 'Open call', amount: 'Fee', deadline: '28 Oct', tone: 'neutral', fit: 'Check' },
  { slug: 'kinetic-drift-co-production', title: 'Kinetic Drift — Co-production 2027', source: 'Tanzfabrik', city: 'Berlin', type: 'Co-production', amount: '€2,000–5,000', deadline: 'Rolling', tone: 'neutral', fit: 'Eligible' },
  { slug: 'sound-development-lab', title: 'Sound Development Lab', source: 'PACT Zollverein', city: 'Cologne', type: 'Lab', amount: 'In-kind', deadline: '14 Nov', tone: 'neutral', fit: 'Check' },
]

function Header({ active = 'Hub' }: { active?: string }) {
  const tabs = [['Hub', '/'], ['Radar', '/radar/brussels'], ['Saved', '/saved'], ['Profile', '/a/roipadan']]
  return <>
    <header className="topbar"><div className="topbar-inner"><Link href="/" className="brand">[間 CUE RADAR]</Link><nav className="desktop-nav" aria-label="Primary navigation">{tabs.map(([label, href]) => <Link className={active === label ? 'nav-link active' : 'nav-link'} href={href} key={label}>{label}</Link>)}</nav><div className="top-actions"><button className="icon-button" aria-label="Search"><Search size={19} /></button><Link href="/a/roipadan" className="avatar">RP</Link></div></div></header><nav className="mobile-nav" aria-label="Mobile navigation">{tabs.map(([label, href], i) => <Link href={href} className={active === label ? 'mobile-nav-link active' : 'mobile-nav-link'} key={label}>{i === 0 ? <Home /> : i === 1 ? <Map /> : i === 2 ? <Bookmark /> : <UserRound />}<span>{label}</span></Link>)}</nav></>
}

function Footer() { return <footer><span>Cue Radar — career OS for independent artists</span><span>Verified feed · updated every 6 h</span></footer> }
function SectionTitle({ children }: { children: React.ReactNode }) { return <div className="section-title">{children}</div> }
function Chip({ children, tone = 'outline' }: { children: React.ReactNode; tone?: string }) { return <span className={`chip ${tone}`}>{children}</span> }

function OpportunityRow({ item }: { item: typeof opportunities[number] }) {
  const [saved, setSaved] = useState(false)
  return <Link href={`/opportunities/${item.slug}`} className="opportunity-row"><div className="row-main"><strong>{item.title}</strong><span>{item.source} · {item.city} · {item.type} · <b>{item.amount}</b></span><small className={item.tone}><i />{item.deadline} <em>{item.fit} {item.fit === 'Eligible' ? '✓' : ''}</em></small></div><button className="save-button" aria-label={saved ? 'Remove from saved' : 'Save opportunity'} onClick={(e) => { e.preventDefault(); setSaved(!saved) }}>{saved ? <Bookmark size={18} fill="currentColor" /> : <Bookmark size={18} />}</button></Link>
}

function Filters() { const [open, setOpen] = useState(false); return <div className="filter-wrap"><div className="mobile-filter-line"><button className="filter-toggle" onClick={() => setOpen(!open)}><span className="live-dot" />For you <ChevronDown size={14} /></button><button className="filter-toggle" onClick={() => setOpen(!open)}>City <ChevronDown size={14} /></button><button className="filter-toggle" onClick={() => setOpen(!open)}>Type <ChevronDown size={14} /></button></div><div className={open ? 'filter-bar open' : 'filter-bar'}>{['City', 'Type', 'Deadline'].map(x => <button className="filter-chip" key={x}>{x}<ChevronDown size={14} /></button>)}<button className="filter-chip">No fee</button><button className="filter-chip">Funded</button><button className="filter-chip">Covers travel</button><button className="reset">Reset</button></div></div> }

function Hub() { return <><Header /><main className="hub-page"><section className="hero"><p>Monday, 14 September</p><h1>61 open deadlines</h1><span>9 closing this week · 3 fit your profile · updated 2 h ago</span></section><Filters /><div className="group-heading"><strong>Closing this week</strong><span>3 · Showing 42 of 61</span></div><section className="opportunity-list">{opportunities.slice(0, 2).map(item => <OpportunityRow item={item} key={item.slug} />)}</section><div className="group-heading later"><strong>This month</strong><span>2 opportunities</span></div><section className="opportunity-list">{opportunities.slice(2).map(item => <OpportunityRow item={item} key={item.slug} />)}</section></main><Footer /></> }

function Profile() { const [expanded, setExpanded] = useState(false); return <><Header active="Profile" /><main className="profile-page"><section className="profile-header"><div className="profile-avatar">RP</div><div><h1>Roi Padan</h1><p>Choreographer · Sound artist</p><span><i /> Currently in Cologne · until 20 Nov</span></div></section><div className="profile-actions"><button className="primary-button">Share</button><button className="outline-button">Export profile</button><button className="text-button">Edit profile</button></div><section className="profile-section bio"><p>Roi Padan is a choreographer and sound artist working between Cologne and Tel Aviv. His practice examines the body as an acoustic instrument, using movement, modular synthesis, and field recording to create live environments where listening becomes physical.</p>{expanded && <p>His work is grounded in duration, resonance, and the unstable space between a gesture and its echo.</p>}<button className="text-button" onClick={() => setExpanded(!expanded)}>{expanded ? 'Show less' : 'Read more'}</button></section><section className="facts-grid"><div><span>Location</span><strong>Cologne · Tel Aviv</strong></div><div><span>Disciplines</span><strong>Dance · Sound</strong></div><div><span>Active since</span><strong>2016</strong></div><div><span>Verified</span><strong>September 2026</strong></div><div><span>Languages</span><strong>Hebrew · English · German</strong></div><div><span>Available from</span><strong>21 Nov 2026</strong></div></section><section className="profile-section"><SectionTitle>Selected works</SectionTitle><div className="work-list"><div><strong>Somatic Echoes</strong><span>Choreography · 2025</span></div><div><strong>Kinetic Drift</strong><span>Live performance · 2024</span></div><div><strong>Bodily Feedback</strong><span>Installation · 2023</span></div></div></section><section className="profile-section"><SectionTitle>Showreel</SectionTitle><div className="showreel"><button aria-label="Play showreel"><Play size={18} fill="currentColor" /></button></div></section><section className="profile-section"><SectionTitle>Gallery</SectionTitle><div className="gallery">{[1,2,3,4].map(n => <div key={n} className={`gallery-image image-${n}`} />)}</div></section></main><Footer /></> }

function Radar() { return <><Header active="Radar" /><main className="wide-page"><section className="radar-heading"><div><p>Trip radar</p><h1>Brussels</h1><span>14–20 Nov 2026</span></div><button className="text-button">Edit trip</button></section><div className="day-strip"><button className="active">14 Nov</button><button>15 Nov</button><button>16 Nov</button><button>17 Nov</button><button>18 Nov</button><button>19 Nov</button><button>20 Nov</button></div><section className="radar-section"><SectionTitle>Deadlines while you&apos;re there</SectionTitle>{opportunities.filter(x => x.city === 'Brussels').map(item => <OpportunityRow item={item} key={item.slug} />)}</section><section className="radar-section"><SectionTitle>Events in Brussels</SectionTitle>{[['Workshop', 'Listening as movement', '14 Nov · 18:00 · Beursschouwburg'], ['Performance', 'The threshold of listening', '16 Nov · 20:30 · Kaaitheater'], ['Meetup', 'Independent artists in Brussels', '18 Nov · 19:00 · Le Lac']].map(([type, title, meta]) => <div className="event-row" key={title}><span>{type}</span><strong>{title}</strong><small>{meta}</small></div>)}</section></main><Footer /></> }

function Saved() { const [tab, setTab] = useState('Saved'); return <><Header active="Saved" /><main className="wide-page"><section className="page-heading"><h1>Pipeline</h1><p>14 saved · 3 drafting · 2 closing this week</p></section><div className="pipeline-tabs">{['Saved','Drafting','Submitted','Accepted','Rejected'].map(x => <button className={tab === x ? 'active' : ''} onClick={() => setTab(x)} key={x}>{x}</button>)}</div><div className="pipeline-board">{(tab === 'Saved' ? opportunities.slice(0,2) : tab === 'Drafting' ? opportunities.slice(2,3) : []).map(item => <Link className="pipeline-card" href={`/opportunities/${item.slug}`} key={item.slug}><span>{item.type} · {item.city}</span><h2>{item.title}</h2><p>{item.source}</p><small className={item.tone}><i />{item.deadline}</small></Link>)}{tab !== 'Saved' && tab !== 'Drafting' && <div className="empty-column">Nothing here yet.</div>}</div></main><Footer /></> }

function OpportunityDetail() { return <><Header /><main className="detail-page opportunity-detail"><p className="breadcrumb">Hub / Residency</p><article><p className="meta-line">Residency · Medium effort · <b>€2,000–5,000</b> · Stipend</p><h1>Body Time Space Residency 2027</h1><p className="location">Radialsystem · Berlin, DE</p><p className="trust"><ShieldCheck size={15} /> Verified 8 Sep 2026 · last checked 12 Sep · source radialsystem.de</p><p className="body-copy">A residency for artists developing new work at the intersection of choreography, sound, and expanded performance. The programme offers time, space, and a production framework in Berlin.</p><SectionTitle>Why you&apos;re eligible</SectionTitle>{['Open to EU residents — you&apos;re based in Cologne', 'Emerging or mid-career', 'Sound or choreography'].map((x, i) => <p className="fit-line" key={x}>{i === 0 ? <Check /> : i === 1 ? <span>?</span> : <X />} {x}</p>)}<SectionTitle>What it covers</SectionTitle><div className="chip-list"><Chip>Housing</Chip><Chip>Travel</Chip><Chip>Studio</Chip><Chip>Per diem</Chip></div><SectionTitle>Materials</SectionTitle>{['CV · In vault', 'Showreel link · Ready', 'Project proposal (2 pages) · Missing', 'Budget · Missing'].map((x, i) => <div className="material-row" key={x}><span>{i < 2 ? <Check /> : <X />}</span>{x}</div>)}<p className="materials-note">You have 2 of 4 materials.</p></article><aside className="opportunity-sidebar"><span>Deadline</span><strong>28 Oct 2026</strong><small>● 12 days · 23:59 CET</small><button className="accent-button">Apply on radialsystem.de ↗</button><button className="outline-button">Save to pipeline</button><button className="outline-button">Add to calendar</button></aside></main></> }

export default function Page() { if (typeof window !== 'undefined') { const path = window.location.pathname; if (path === '/a/roipadan') return <Profile />; if (path === '/saved') return <Saved />; if (path === '/radar/brussels') return <Radar />; if (path.startsWith('/opportunities/')) return <OpportunityDetail /> } return <Hub /> }
